import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer"
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "MESMERISE | DIGITAL MARKETING | BRAND STRATEGY",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (

    <html lang="en">
    <body className={`${geistSans.variable} ${geistMono.variable} bg-black text-[var(--foreground)]`}>
            <Header />

        {children}

        <Footer />
      </body>
    </html>
  );
}
