/** @type {import("next").Viewport} */
import Header from "@/components/layout/header";
import MenuToggle from "@/components/ui/MenuToggle";
import Footer from "@/components/layout/footer";
import Inner from "@/components/layout/Inner";
import Template from "@/components/layout/template";
import BodyThemeWrapper from "@/components/layout/BodyThemeWrapper";
import "./globals.css";

export const metadata = {
  title: "MESMERISE | DIGITAL MARKETING | BRAND STRATEGY",
  description: "Generated by create next app",
};
export const viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={"bg-[var(--background)] text-[var(--foreground)]"}>
        <BodyThemeWrapper />
        <Header />
        <Template>
          <Inner>{children}</Inner>
        </Template>
        <MenuToggle />
        <Footer />
        <script src="node_modules/eruda/eruda.js"></script>
        <script>eruda.init();</script>
      </body>
    </html>
  );
}
