/** @type {import("next").Viewport} */
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer"
import Inner from "@/components/layout/Inner"
import BodyThemeWrapper from "@/components/layout/BodyThemeWrapper";
import "./globals.css";

export const metadata = {
  title: "MESMERISE | DIGITAL MARKETING | BRAND STRATEGY",
  description: "Generated by create next app",

};
export const viewport = {
    width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
}

export default function RootLayout({ children }) {
  return (

    <html lang="en">
    <body className={"bg-[var(--background)] text-[var(--foreground)]"}>
      <BodyThemeWrapper />
        <Header />
          <Inner>
            {children}
          </Inner>
        <Footer />
      </body>
    </html>
  );
}
